python_sources(  # takes all the *.py files (not ending with _test.py) by default
    name="lib",
)

# Create a pex binary for the entire application
pex_binary(
    name="pex_binary",
    entry_point="__init__.py",
)
