name: "Reports - Unit Tests"

on:
  push:
    branches:
      - master
    paths:
      - "libs/reports/**"
  pull_request:
    paths:
      - "libs/reports/**"

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v4
      - name: Formatting
        uses: psf/black@stable
      - name: Linting
        uses: py-actions/flake8@v2

  unittest:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v4
      - name: Install Project
        run: |
          python -m pip install --upgrade pip
          pip install -e libs/reports
      - name: Run tests
        run: pytest libs/reports/test/unit
